### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by josearodrigueze** [kuzmoyev/google-calendar-simple-api#136]
I need some help, because i used but when i run de backend stop here and never continue 

![image](https://user-images.githubusercontent.com/7081637/168704413-6b81848e-0bf3-4c24-b582-a75bb509dd5a.png)

I loggin and get redirect but doesn't work

**Comment by kuzmoyev** [comment]
It's not a lot of information to work with. One thing that might be an issue when running it in docker is that you need to expose the `8080` port so that after authorization flow the response is sent to it.

Please use [GitHub Discussions](https://github.com/kuzmoyev/google-calendar-simple-api/discussions) or a [Discord](https://discord.gg/mRAegbwYKS) for questions in the future.

**Comment by kuzmoyev** [comment]
Closing the issue. If you want to discuss it more, please do so in Discussions or Discord.
