### ISSUE TITLE
Deleting events based on string

### ISSUE THREAD

**Issue by TheXer** [kuzmoyev/google-calendar-simple-api#72]
Hello, i would like to write an issue again, this time with events. 

I would like to an user to write an input (string name of the event) and based on the name the code would find it and delete by itself. 

Python 3.8.2, MacOS Big Sur. 

Code below:

```
async def remove(ctx, name:str):
    
    calendar.get_events(query=name)
    calendar.delete_event(name)
    await ctx.send('Event "{}" se úspěšně smazal.'.format(name))
```
    
this is just a function. Event is declared in different function. 

```
async def create(ctx, name:str, datestring:str, hours_begin: typing.Optional[str], hours_after: typing.Optional[str]):
    separator = "."
    separator_hours = ":"

    if hours_begin and hours_after != None:
        day, month, year = (int(i) for i in datestring.split(separator))
        hours, minutes = (int(i) for i in hours_begin.split(separator_hours))
        hour_after, minute_after = (int(i) for i in hours_after.split(separator_hours))

        datetime_begin = datetime.datetime(day = day, month = month , year = year, hour = hours, minute = minutes)
        datetime_last = datetime.datetime(day = day, month = month, year = year, hour = hour_after, minute = minute_after)

        event = Event(name, datetime_begin, datetime_last)

    else:
        day, month, year = (int(i) for i in datestring.split(separator))
        datetime_begin = datetime.date(day = day, month = month , year = year)

        event = Event(name, datetime_begin)

    try:
        calendar.add_event(event)
        await ctx.send('Event "{}" se úspěšně přidal do kalendáře.'.format(name))
    except: 
        await ctx.send("Event se nepřidal.")
```
        
Have you got any workaround for this? I'm sorry if I'm being unhelpful, I'm somewhat of beginner. 

edit: formatting

**Comment by kuzmoyev** [comment]
@TheXer 
`calendar.get_events(query=name)` would return a list of events. Now pass event from this list to `calendar.delete_event(event)` (instead of the `name`).

I'd also suggest checking the name in the event (if you want it to be exactly the same as the `name` you pass to your function). Because it is a query in  `get_events` and it is processed by google and who know how it filters them :)

Also in the future, if you have a question, not an actual issue or suggestion, you can try [creating a new discussion](https://github.com/kuzmoyev/google-calendar-simple-api/discussions) (haven't tried them myself but looks like a better place for these kinds of questions).

**Comment by TheXer** [comment]
You are awesome! Thanks for your time for responding to an actual beginner like me! :-) I'll look into discussions, thanks for suggestion!
